name: Build & Deploy WebGL

on:
  push:
    branches: [ "build" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2️⃣ Демонстрация запуска CI
      - name: CI started
        run: echo "CI started!"

      # 3️⃣ Сборка Unity WebGL
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          unityVersion: auto
          projectPath: ./Test git project  # <- корень Unity проекта
          buildsPath: build
          buildName: WebGLBuild
