name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - main  # или ваша ветка

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Unity
      uses: game-ci/unity-actions/setup@v2
      with:
        unityVersion: 6000.0.44f1  

    - name: Build WebGL
      uses: game-ci/unity-actions/build@v2
      with:
        targetPlatform: WebGL
        buildPath: Build/WebGL

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: webgl-build
        path: Build/WebGL

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: webgl-build
        path: Build/WebGL

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Build/WebGL
