name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - build  # ветка с Unity проектом

jobs:
  build-deploy:
    name: Build WebGL and Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Кэшируем Library для ускорения сборок
    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Test git project/Library
        key: ${{ runner.os }}-unity-${{ hashFiles('Test git project/Assets/**/*') }}

    # 3️⃣ Сборка WebGL с автоматической активацией Personal лицензии
    - name: Build WebGL
      uses: game-ci/unity-builder@v3
      with:
        projectPath: "Test git project"
        targetPlatform: WebGL
        buildPath: "Build/WebGL"
        unityVersion: 6000.0.44f1
        unityLicense: ${{ secrets.UNITY_LICENSE }}

    # 4️⃣ Публикация на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: build        # пушим в ту же ветку
        publish_dir: Build/WebGL     # папка с index.html для Pages
