name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - build

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий
    - uses: actions/checkout@v3

    # 2️⃣ Кэшируем Library для ускорения сборок
    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Test git project/Library
        key: ${{ runner.os }}-unity-${{ hashFiles('Test git project/Assets/**/*') }}

    # 3️⃣ Сборка WebGL
    - name: Build WebGL
      uses: game-ci/unity-builder@v4
      with:
        unityVersion: 6.0.44f1
        projectPath: "Test git project"
        targetPlatform: WebGL
        buildsPath: "Build"
        buildName: "WebGL"

    # 4️⃣ Деплой на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: build
        publish_dir: Build/WebGL
