name: Build WebGL

on:
  push:
    branches: [ "build" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: CI started!
        run: echo "CI started!"

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          unityVersion: auto
          buildsPath: build
          buildName: WebGLBuild
          activateLicense: false  # <- для Personal License

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/WebGLBuild

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
