name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - build

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий
    - uses: actions/checkout@v3

    # 2️⃣ Кэшируем Library для ускорения сборок
    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Test git project/Library
        key: ${{ runner.os }}-unity-${{ hashFiles('Test git project/Assets/**/*') }}

    # --- Активируйте Unity (вариант: game-ci activation / manual ULF) ---
    # Этот шаг нужен только если вы собираетесь реально запускать Editor.
    # Инструкции по подготовке секретов и созданию .ulf см. в документации GameCI (ниже).
    - name: Activate Unity (GameCI)
    if: ${{ secrets.UNITY_LICENSE != '' }}
    uses: game-ci/unity-activate@v2
    with:
        # пример: передадим содержимое .ulf в секрет UNITY_LICENSE
        license: ${{ secrets.UNITY_LICENSE }}

    # 3️⃣ Сборка WebGL
    - name: Build WebGL
      uses: game-ci/unity-builder@v4
      with:
        unityVersion: auto
        projectPath: "Test git project"
        targetPlatform: WebGL
        buildsPath: "Build"
        buildName: "WebGL"

    # 4️⃣ Деплой на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: build
        publish_dir: Build/WebGL
