name: Build and Deploy Unity WebGL

on:
  push:
    branches:
      - build

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Клонируем репозиторий
    - uses: actions/checkout@v3

    # 2️⃣ Кэшируем Library для ускорения сборок
    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Test git project/Library
        key: ${{ runner.os }}-unity-${{ hashFiles('Test git project/Assets/**/*') }}

    - name: Request a Unity license file
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_TOTP_KEY: ${{ secrets.UNITY_TOTP_KEY }}
        run: |
          npm install
          npm install -g .
          unity-license-activate "$UNITY_EMAIL" "$UNITY_PASSWORD" Unity_v${{ matrix.unityVersion }}.alf --authenticator-key "$UNITY_TOTP_KEY"

      - name: Activate License
        run: |
          unity-editor -quit -batchmode -nographics -logFile -manualLicenseFile $(ls Unity_*.ulf) || true
          rm Unity_*.ulf
          rm Unity_*.alf

    # 3️⃣ Сборка WebGL
    - name: Build WebGL
      uses: game-ci/unity-builder@v4
      with:
        unityVersion: auto
        projectPath: "Test git project"
        targetPlatform: WebGL
        buildsPath: "Build"
        buildName: "WebGL"

    # 4️⃣ Деплой на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: build
        publish_dir: Build/WebGL
